services:
  core:
    build:
      context: .
      dockerfile: core.dockerfile
    container_name: Core
    networks:
      - mynetwork
    ports:
      - "50051:50051"

  grading:
    build:
      context: ./plugins/grading
      dockerfile: grading.dockerfile
    container_name: Grading
    volumes:
      - ./plugins/grading:/app
    networks:
      - mynetwork
    depends_on:
      - hivemq
    environment:
      - MQTT_BROKER=hivemq:1883
    ports:
      - "50052:50052" 

  hivemq:
    image: hivemq/hivemq4
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "8080:8080"
    networks:
      - mynetwork

  cutting:
    build:
      context: ./plugins/cutting
      dockerfile: cutting.dockerfile
    container_name: Cutting
    volumes:
      - ./plugins/cutting:/app
    networks:
      - mynetwork
    ports:
      - "50053:50053" 

networks:
  mynetwork:
    driver: bridge
