services:
  core:
    build:
      context: .
      dockerfile: core.dockerfile
    container_name: Core
    environment:
      - MQTT_BROKER=ssl://34f3f472652e44989715e359655e32dc.s1.eu.hivemq.cloud:8883
      - CLIENT_ID=CoreClient
      - MQTT_USERNAME=harith
      - MQTT_PASSWORD=Harith123
    ports:
      - "50051:50051"

  grading:
    build:
      context: ./plugins/grading
      dockerfile: grading.dockerfile
    container_name: Grading
    volumes:
      - ./plugins/grading:/app
    environment:
      - MQTT_BROKER=ssl://34f3f472652e44989715e359655e32dc.s1.eu.hivemq.cloud:8883
      - CLIENT_ID=GradingPluginSubscriber
      - MQTT_USERNAME=harith
      - MQTT_PASSWORD=Harith123
    ports:
      - "50052:50052" 

  cutting:
    build:
      context: ./plugins/cutting
      dockerfile: cutting.dockerfile
    container_name: Cutting
    volumes:
      - ./plugins/cutting:/app
    ports:
      - "50053:50053"