version: '3.8'

services:
  core:
    build:
      context: .
      dockerfile: core.dockerfile
    container_name: Core
    networks:
      - mynetwork
    ports:
      - "50051:50051"

  grading:
    build:
      context: ./plugins/grading
      dockerfile: grading.dockerfile
    container_name: Grading
    volumes:
      - ./plugins/grading:/app
    networks:
      - mynetwork
    ports:
      - "50052:50052" 

  cutting:
    build:
      context: ./plugins/cutting
      dockerfile: cutting.dockerfile
    container_name: Cutting
    volumes:
      - ./plugins/cutting:/app
    networks:
      - mynetwork
    ports:
      - "50053:50053" 

networks:
  mynetwork:
    driver: bridge
