apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-system
  template:
    metadata:
      labels:
        app: core-system
    spec:
      containers:
        - name: core-system
          image: harith2001/coconut-peat-supply-chain_core_system-core:latest
          ports:
            - containerPort: 50051
          env:
            - name: MQTT_BROKER
              value: "ssl://34f3f472652e44989715e359655e32dc.s1.eu.hivemq.cloud:8883"
            - name: CLIENT_ID
              value: "CoreClient"
            - name: MQTT_USERNAME
              value: "harith"
            - name: MQTT_PASSWORD
              value: "Harith123"

---
apiVersion: v1
kind: Service
metadata:
  name: core-system-service
spec:
  selector:
    app: core-system
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30001
  type: NodePort
