apiVersion: apps/v1
kind: Deployment
metadata:
  name: grading-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grading-plugin
  template:
    metadata:
      labels:
        app: grading-plugin
    spec:
      containers:
        - name: grading-plugin
          image: harith2001/coco-grading:latest
          ports:
            - containerPort: 50052
          env:
            - name: MQTT_BROKER
              value: "ssl://34f3f472652e44989715e359655e32dc.s1.eu.hivemq.cloud:8883"
            - name: CLIENT_ID
              value: "GradingPluginSubscriber"
            - name: MQTT_USERNAME
              value: "harith"
            - name: MQTT_PASSWORD
              value: "Harith123"

---
apiVersion: v1
kind: Service
metadata:
  name: grading-plugin-service
spec:
  selector:
    app: grading-plugin
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP
