apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: all-pods-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels: {}  # Match all services
  namespaceSelector:
    any: true  # Monitor all namespaces
  endpoints:
    - port: 50051
      path: /metrics
      interval: 15s
    - port: 50052
      path: /metrics
      interval: 15s
    - port: 50053
      path: /metrics
      interval: 15s
    - port: 30001
      path: /metrics
      interval: 15s
