// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/plugin_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GradingPlugin_RegisterPlugin_FullMethodName   = "/plugin.GradingPlugin/RegisterPlugin"
	GradingPlugin_ExecutePlugin_FullMethodName    = "/plugin.GradingPlugin/ExecutePlugin"
	GradingPlugin_UnregisterPlugin_FullMethodName = "/plugin.GradingPlugin/UnregisterPlugin"
)

// GradingPluginClient is the client API for GradingPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GradingPluginClient interface {
	RegisterPlugin(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*PluginResponse, error)
	ExecutePlugin(ctx context.Context, in *PluginExecute, opts ...grpc.CallOption) (*ExecutionStatus, error)
	UnregisterPlugin(ctx context.Context, in *PluginUnregister, opts ...grpc.CallOption) (*UnregisterResponse, error)
}

type gradingPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewGradingPluginClient(cc grpc.ClientConnInterface) GradingPluginClient {
	return &gradingPluginClient{cc}
}

func (c *gradingPluginClient) RegisterPlugin(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*PluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginResponse)
	err := c.cc.Invoke(ctx, GradingPlugin_RegisterPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradingPluginClient) ExecutePlugin(ctx context.Context, in *PluginExecute, opts ...grpc.CallOption) (*ExecutionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionStatus)
	err := c.cc.Invoke(ctx, GradingPlugin_ExecutePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradingPluginClient) UnregisterPlugin(ctx context.Context, in *PluginUnregister, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, GradingPlugin_UnregisterPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GradingPluginServer is the server API for GradingPlugin service.
// All implementations must embed UnimplementedGradingPluginServer
// for forward compatibility.
type GradingPluginServer interface {
	RegisterPlugin(context.Context, *PluginRequest) (*PluginResponse, error)
	ExecutePlugin(context.Context, *PluginExecute) (*ExecutionStatus, error)
	UnregisterPlugin(context.Context, *PluginUnregister) (*UnregisterResponse, error)
	mustEmbedUnimplementedGradingPluginServer()
}

// UnimplementedGradingPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGradingPluginServer struct{}

func (UnimplementedGradingPluginServer) RegisterPlugin(context.Context, *PluginRequest) (*PluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPlugin not implemented")
}
func (UnimplementedGradingPluginServer) ExecutePlugin(context.Context, *PluginExecute) (*ExecutionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePlugin not implemented")
}
func (UnimplementedGradingPluginServer) UnregisterPlugin(context.Context, *PluginUnregister) (*UnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterPlugin not implemented")
}
func (UnimplementedGradingPluginServer) mustEmbedUnimplementedGradingPluginServer() {}
func (UnimplementedGradingPluginServer) testEmbeddedByValue()                       {}

// UnsafeGradingPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GradingPluginServer will
// result in compilation errors.
type UnsafeGradingPluginServer interface {
	mustEmbedUnimplementedGradingPluginServer()
}

func RegisterGradingPluginServer(s grpc.ServiceRegistrar, srv GradingPluginServer) {
	// If the following call pancis, it indicates UnimplementedGradingPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GradingPlugin_ServiceDesc, srv)
}

func _GradingPlugin_RegisterPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingPluginServer).RegisterPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingPlugin_RegisterPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingPluginServer).RegisterPlugin(ctx, req.(*PluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradingPlugin_ExecutePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginExecute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingPluginServer).ExecutePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingPlugin_ExecutePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingPluginServer).ExecutePlugin(ctx, req.(*PluginExecute))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradingPlugin_UnregisterPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginUnregister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingPluginServer).UnregisterPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingPlugin_UnregisterPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingPluginServer).UnregisterPlugin(ctx, req.(*PluginUnregister))
	}
	return interceptor(ctx, in, info, handler)
}

// GradingPlugin_ServiceDesc is the grpc.ServiceDesc for GradingPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GradingPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.GradingPlugin",
	HandlerType: (*GradingPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPlugin",
			Handler:    _GradingPlugin_RegisterPlugin_Handler,
		},
		{
			MethodName: "ExecutePlugin",
			Handler:    _GradingPlugin_ExecutePlugin_Handler,
		},
		{
			MethodName: "UnregisterPlugin",
			Handler:    _GradingPlugin_UnregisterPlugin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin_service.proto",
}
